name: Setup Google Cloud
description: Authenticate to GCP via Workload Identity Federation and install gcloud.

runs:
  using: composite
  steps:
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/106595059298/locations/global/workloadIdentityPools/github/providers/github
        service_account: github@n6k-io.iam.gserviceaccount.com
        token_format: access_token
        create_credentials_file: true

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
