// AUTO-GENERATED by packages/python/src/n6k_protocol/codegen.py — DO NOT EDIT.
// Source of truth: packages/python/src/n6k_protocol/protocol.py
// Regenerate via `make protocol-gen`.

#pragma once

#include <cstdint>

namespace duckdb {
namespace n6k {

constexpr int N6K_PROTOCOL_VERSION = 6;

enum class FrameType : uint8_t {
	REQ = 1,
	RESP_SCHEMA = 2,
	RESP_CHUNK = 3,
	RESP_END = 4,
	ERR = 5,
	CANCEL = 6,
	CREDIT = 7,
	PUSH = 8,
	PING = 9,
	PONG = 10,
	HELLO = 11,
	HELLO_ACK = 12,
	HELLO_ERR = 13,
	READY = 14,
};

constexpr uint8_t FLAG_END_OF_STREAM = 0x01;
constexpr uint8_t FLAG_COMPRESSED = 0x02;
constexpr uint8_t FLAG_IS_ARROW_IPC = 0x04;

constexpr uint8_t OP_CATALOG_LIST = 1;
constexpr uint8_t OP_TABLES_LIST = 2;
constexpr uint8_t OP_TABLE_SCHEMA = 3;
constexpr uint8_t OP_SCAN = 4;
constexpr uint8_t OP_INSERT = 5;
constexpr uint8_t OP_EXEC = 6;
constexpr uint8_t OP_QUERY = 7;
constexpr uint8_t OP_RPC_SCALAR = 8;
constexpr uint8_t OP_RPC_TABLE = 9;
constexpr uint8_t OP_CREATE_TABLE = 10;
constexpr uint8_t OP_ALTER_TABLE = 11;
constexpr uint8_t OP_CATALOG_INVALIDATED = 12;
constexpr uint8_t OP_AGGREGATE = 13;

constexpr int DEFAULT_BATCH_CREDITS = 8;
constexpr int MAX_CONCURRENT_REQS = 64;
constexpr const char *CAP_AGGREGATE_PUSHDOWN = "aggregate_pushdown";

} // namespace n6k
} // namespace duckdb
