"""Generate the TypeScript and C++ mirrors of `n6k_protocol.protocol`.

Invoked by `make protocol-gen`. Writes:
  - packages/npm/src/protocol-generated.ts
  - src/common/include/n6k_protocol_generated.hpp
  - packages/python/src/n6k_protocol/schema.json (read at runtime by engine.py)

`make protocol-check` runs this and asserts no diff against the committed
files — drift = bug.
"""

from __future__ import annotations

import json
import os
import sys

from n6k_protocol import protocol as P

# packages/python/src/n6k_protocol/codegen.py → repo root is 4 levels up
REPO_ROOT = os.path.realpath(os.path.join(os.path.dirname(__file__), "..", "..", "..", ".."))
TS_OUT = os.path.join(REPO_ROOT, "packages", "npm", "src", "protocol-generated.ts")
HPP_OUT = os.path.join(REPO_ROOT, "src", "common", "include", "n6k_protocol_generated.hpp")
SCHEMA_OUT = os.path.join(REPO_ROOT, "packages", "python", "src", "n6k_protocol", "schema.json")

TS_HEADER = """// AUTO-GENERATED by packages/python/src/n6k_protocol/codegen.py — DO NOT EDIT.
// Source of truth: packages/python/src/n6k_protocol/protocol.py
// Regenerate via `make protocol-gen`.
"""

HPP_HEADER = """// AUTO-GENERATED by packages/python/src/n6k_protocol/codegen.py — DO NOT EDIT.
// Source of truth: packages/python/src/n6k_protocol/protocol.py
// Regenerate via `make protocol-gen`.
"""


def render_ts() -> str:
    lines = [TS_HEADER]
    lines.append(f"export const N6K_PROTOCOL_VERSION = {P.N6K_PROTOCOL_VERSION};")
    lines.append("")
    lines.append("export const FT = {")
    for name, value in P._FRAME_TYPES:
        lines.append(f"  {name}: {value},")
    lines.append("} as const;")
    lines.append("")
    lines.append("export const OP = {")
    for name, value in P._OPS:
        lines.append(f"  {name}: {value},")
    lines.append("} as const;")
    lines.append("")
    for name, value in P._FLAGS:
        lines.append(f"export const FLAG_{name} = 0x{value:02x};")
    lines.append("")
    lines.append(f"export const DEFAULT_BATCH_CREDITS = {P.DEFAULT_BATCH_CREDITS};")
    lines.append(f"export const MAX_CONCURRENT_REQS = {P.MAX_CONCURRENT_REQS};")
    lines.append(f'export const CAP_AGGREGATE_PUSHDOWN = "{P.CAP_AGGREGATE_PUSHDOWN}";')
    lines.append("")
    return "\n".join(lines)


def render_hpp() -> str:
    lines = [HPP_HEADER]
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace duckdb {")
    lines.append("namespace n6k {")
    lines.append("")
    lines.append(f"constexpr int N6K_PROTOCOL_VERSION = {P.N6K_PROTOCOL_VERSION};")
    lines.append("")
    lines.append("enum class FrameType : uint8_t {")
    for name, value in P._FRAME_TYPES:
        lines.append(f"\t{name} = {value},")
    lines.append("};")
    lines.append("")
    for name, value in P._FLAGS:
        lines.append(f"constexpr uint8_t FLAG_{name} = 0x{value:02x};")
    lines.append("")
    for name, value in P._OPS:
        lines.append(f"constexpr uint8_t OP_{name} = {value};")
    lines.append("")
    lines.append(f"constexpr int DEFAULT_BATCH_CREDITS = {P.DEFAULT_BATCH_CREDITS};")
    lines.append(f"constexpr int MAX_CONCURRENT_REQS = {P.MAX_CONCURRENT_REQS};")
    lines.append(f'constexpr const char *CAP_AGGREGATE_PUSHDOWN = "{P.CAP_AGGREGATE_PUSHDOWN}";')
    lines.append("")
    lines.append("} // namespace n6k")
    lines.append("} // namespace duckdb")
    lines.append("")
    return "\n".join(lines)


def render_schema_json() -> str:
    """Render `_FRAME_HEADERS` into a JSON-Schema document whose root is a
    `oneOf` of per-frame header objects. Each variant pins `t` (and, for
    REQ/PUSH, `op`) as a `const`, so the variants are mutually exclusive and a
    decoded header matches exactly one. `engine.validate_header()` enforces this
    schema; the TS/C++ codecs read header fields directly."""
    doc = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$comment": (
            "AUTO-GENERATED by packages/python/src/n6k_protocol/codegen.py - DO NOT EDIT. "
            "Source of truth: packages/python/src/n6k_protocol/protocol.py. "
            "Regenerate via `make protocol-gen`."
        ),
        "title": "n6k frame header",
        "description": "The msgpack header map of one n6k wire frame (a raw Arrow body may follow).",
        "oneOf": [P.header_variant_schema(v) for v in P._FRAME_HEADERS],
    }
    return json.dumps(doc, indent=2) + "\n"


def write_if_changed(path: str, content: str) -> bool:
    existing = None
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            existing = f.read()
    if existing == content:
        return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return True


def main() -> int:
    changed = []
    if write_if_changed(TS_OUT, render_ts()):
        changed.append(os.path.relpath(TS_OUT, REPO_ROOT))
    if write_if_changed(HPP_OUT, render_hpp()):
        changed.append(os.path.relpath(HPP_OUT, REPO_ROOT))
    schema_json = render_schema_json()
    if write_if_changed(SCHEMA_OUT, schema_json):
        changed.append(os.path.relpath(SCHEMA_OUT, REPO_ROOT))
    if changed:
        print("regenerated:")
        for p in changed:
            print(f"  {p}")
    else:
        print("up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
