// AUTO-GENERATED by packages/python/src/n6k_protocol/codegen.py — DO NOT EDIT.
// Source of truth: packages/python/src/n6k_protocol/protocol.py
// Regenerate via `make protocol-gen`.

export const N6K_PROTOCOL_VERSION = 6;

export const FT = {
  REQ: 1,
  RESP_SCHEMA: 2,
  RESP_CHUNK: 3,
  RESP_END: 4,
  ERR: 5,
  CANCEL: 6,
  CREDIT: 7,
  PUSH: 8,
  PING: 9,
  PONG: 10,
  HELLO: 11,
  HELLO_ACK: 12,
  HELLO_ERR: 13,
  READY: 14,
} as const;

export const OP = {
  CATALOG_LIST: 1,
  TABLES_LIST: 2,
  TABLE_SCHEMA: 3,
  SCAN: 4,
  INSERT: 5,
  EXEC: 6,
  QUERY: 7,
  RPC_SCALAR: 8,
  RPC_TABLE: 9,
  CREATE_TABLE: 10,
  ALTER_TABLE: 11,
  CATALOG_INVALIDATED: 12,
  AGGREGATE: 13,
} as const;

export const FLAG_END_OF_STREAM = 0x01;
export const FLAG_COMPRESSED = 0x02;
export const FLAG_IS_ARROW_IPC = 0x04;

export const DEFAULT_BATCH_CREDITS = 8;
export const MAX_CONCURRENT_REQS = 64;
export const CAP_AGGREGATE_PUSHDOWN = "aggregate_pushdown";
