name: packages/npm lint & test

on:
  push:
    paths:
      - "packages/npm/**"
  pull_request:
    paths:
      - "packages/npm/**"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/npm
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - run: bun lint

      - run: bun test
        env:
          BACKEND: skip
          TEST_SERVER: skip
